<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : English (American)
// Author of the language pack : MyBB Group
// Language pack translators website : https://mybb.com/
// Compatible version of MyBB : 1828
// Last edited in MyBB Editor by : Matty Wjeisz
// Last edited date : Sun, 24 Jul 2022 15:26:07 +0000
// --------------------------------------------------------------------------------

$l['nav_announcements'] = 'Announcement';
$l['announcements'] = 'Announcement';
$l['forum_announcement'] = '{1}';
$l['error_invalidannouncement'] = 'The announcement specified is invalid.';
$l['announcement_edit'] = 'Edit this announcement';
$l['announcement_qdelete'] = 'Delete this announcement';
$l['announcement_quickdelete_confirm'] = 'Are you sure you want to delete this announcement?';
