<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : English (American)
// Author of the language pack : MyBB Group
// Language pack translators website : https://mybb.com/
// Compatible version of MyBB : 1837
// Last edited in MyBB Editor by : Matty
// Last edited date : Mon, 22 Jan 2024 23:23:01 +0000
// --------------------------------------------------------------------------------

$l['boardstats'] = 'Board Statistics';
$l['new_posts'] = 'New Posts';
$l['no_new_posts'] = 'No New Posts';
$l['forum_closed'] = 'Closed';
$l['forum_unapproved_posts_count'] = 'There are currently {1} unapproved posts in this forum.';
$l['forum_unapproved_post_count'] = 'There is currently 1 unapproved post in this forum.';
$l['forum_unapproved_threads_count'] = 'There is currently {1} unapproved threads in this forum.';
$l['forum_unapproved_thread_count'] = 'There is currently 1 unapproved thread in this forum.';
$l['forumstats'] = 'Statistics <i class="bi bi-chevron-right"></i>';
$l['todays_birthdays'] = 'Today\'s Birthdays';
$l['birthdayhidden'] = 'Hidden';
$l['quick_login'] = 'Quick Login:';
$l['index_logout'] = 'Log Out';
$l['private_messages'] = 'Private Messages';
$l['pms_new'] = 'You have {1} new messages.';
$l['pms_unread_total'] = '(You have {1} unread messages and {2} total messages in all of your folders.)';
$l['stats_posts_threads'] = '<div class="col align-self-center text-center catmod p-3">Posts <span class="text-muted">{1}</span></div><div class="col align-self-center text-center catmod p-3">Threads <span class="text-muted">{2}</span></div>';
$l['stats_numusers'] = '<div class="col align-self-center text-center catmod p-3">Members <span class="text-muted">{1}</span></div>';
$l['stats_newestuser'] = '<div class="col align-self-center text-center catmod p-3">Latest user {1}</div>';
$l['stats_mostonline'] = 'Most users online {1}';
$l['whos_online'] = 'Recently Browsing';
$l['complete_list'] = 'Who\'s Online';
$l['online_online_plural'] = 'users';
$l['online_online_singular'] = 'user';
$l['online_member_plural'] = 'members';
$l['online_member_singular'] = 'member';
$l['online_anon_plural'] = 'are';
$l['online_anon_singular'] = 'is';
$l['online_guest_plural'] = 'guests';
$l['online_guest_singular'] = 'guest';
$l['online_note'] = '{1} users online ({4} {5}, {8} {9})';
$l['subforums'] = 'Sub Forums:';
$l['board_stats_link_separator'] = ' | ';
