<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : English (American)
// Author of the language pack : MyBB Group
// Language pack translators website : https://mybb.com/
// Compatible version of MyBB : 1828
// Last edited in MyBB Editor by : Matty Wjeisz
// Last edited date : Thu, 28 Jul 2022 05:17:41 +0000
// --------------------------------------------------------------------------------

$l['nav_memberlist'] = 'Members';
$l['memberlist_disabled'] = 'The member list functionality has been disabled by the Administrator.';
$l['member_list'] = 'Members';
$l['avatar'] = 'Avatar';
$l['username'] = 'Member';
$l['joined'] = 'Joined';
$l['lastvisit'] = 'Last Visit';
$l['posts'] = 'Posts';
$l['threads'] = 'Threads';
$l['referrals'] = 'Referrals';
$l['search_members'] = 'Search Members';
$l['website'] = 'Website';
$l['sort_by'] = 'Sort by';
$l['contains'] = 'Contains';
$l['exactly'] = 'Exactly';
$l['sort_by_username'] = 'Sort by: Username';
$l['sort_by_regdate'] = 'Sort by: Registration date';
$l['sort_by_lastvisit'] = 'Sort by: Last visit';
$l['sort_by_posts'] = 'Sort by: Post count';
$l['sort_by_threads'] = 'Sort by: Thread count';
$l['sort_by_referrals'] = 'Sort by: Members referred';
$l['order_asc'] = 'ascending order';
$l['order_desc'] = 'descending order';
$l['asc'] = 'asc';
$l['desc'] = 'desc';
$l['forumteam'] = 'Show Forum Team';
$l['advanced_search'] = 'Advanced Search';
$l['nav_memberlist_search'] = 'Search';
$l['search_member_list'] = 'Search Members';
$l['search_criteria'] = 'Search Criteria';
$l['begins_with'] = 'begins with';
$l['username_contains'] = 'contains';
$l['username_exact'] = 'exactly';
$l['search_website'] = 'Website';
$l['search_skype'] = 'Skype';
$l['search_google'] = 'Google Hangouts';
$l['search_icq'] = 'ICQ Number';
$l['search_options'] = 'Search Options';
$l['per_page'] = 'Results Per Page';
$l['search'] = 'Search';
$l['error_no_members'] = '<p>There were no members found with the search criteria you entered.</p><p>Please enter a different search term and try again.</p>';
$l['a'] = 'A';
$l['b'] = 'B';
$l['c'] = 'C';
$l['d'] = 'D';
$l['e'] = 'E';
$l['f'] = 'F';
$l['g'] = 'G';
$l['h'] = 'H';
$l['i'] = 'I';
$l['j'] = 'J';
$l['k'] = 'K';
$l['l'] = 'L';
$l['m'] = 'M';
$l['n'] = 'N';
$l['o'] = 'O';
$l['p'] = 'P';
$l['q'] = 'Q';
$l['r'] = 'R';
$l['s'] = 'S';
$l['t'] = 'T';
$l['u'] = 'U';
$l['v'] = 'V';
$l['w'] = 'W';
$l['x'] = 'X';
$l['y'] = 'Y';
$l['z'] = 'Z';
