<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : English (American)
// Author of the language pack : MyBB Group
// Language pack translators website : https://mybb.com/
// Compatible version of MyBB : 1828
// Last edited in MyBB Editor by : Matty Wjeisz
// Last edited date : Sun, 24 Jul 2022 14:30:31 +0000
// --------------------------------------------------------------------------------

$l['nav_sendthread'] = 'Send Thread';
$l['send_thread'] = 'Send Thread';
$l['recipient'] = 'Recipient';
$l['recipient_note'] = 'Enter your friends email address here.';
$l['subject'] = 'Subject';
$l['message'] = 'Message';
$l['error_nosubject'] = 'You are required to enter a subject for the message to send your thread';
$l['error_nomessage'] = 'You are required to enter a message before you can send this thread to your friend';
