<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : English (American)
// Author of the language pack : MyBB Group
// Language pack translators website : https://mybb.com/
// Compatible version of MyBB : 1837
// Last edited in MyBB Editor by : Matty
// Last edited date : Wed, 24 Jan 2024 07:51:09 +0000
// --------------------------------------------------------------------------------

$l['delete_poll'] = 'Delete Poll';
$l['close_thread'] = 'Close Thread';
$l['stick_thread'] = 'Stick Thread';
$l['author'] = 'Author';
$l['message'] = 'Message';
$l['threaded'] = '<i class="bi bi-list-nested" title="Threaded Mode"></i>';
$l['linear'] = '<i class="bi bi-list" title="Linear Mode"></i>';
$l['next_oldest'] = 'Next Oldest';
$l['next_newest'] = 'Next Newest';
$l['view_printable'] = 'Print Thread';
$l['send_thread'] = 'Share Post';
$l['subscribe_thread'] = '<i class="bi bi-bell"></i> Follow';
$l['unsubscribe_thread'] = '<i class="bi bi-bell-slash"></i> Unfollow';
$l['add_poll_to_thread'] = 'Add Poll';
$l['moderation_options'] = 'Mod Options';
$l['delayed_moderation'] = 'Delayed Moderation';
$l['thread_notes'] = 'Edit / View Thread Notes';
$l['open_close_thread'] = 'Open / Close Thread';
$l['approve_thread'] = 'Approve Thread';
$l['unapprove_thread'] = 'Unapprove Thread';
$l['soft_delete_thread'] = 'Soft Delete Thread';
$l['restore_thread'] = 'Restore Thread';
$l['delete_thread'] = 'Delete Thread Permanently';
$l['delete_posts'] = 'Delete Selective Posts';
$l['move_thread'] = 'Move / Copy Thread';
$l['stick_unstick_thread'] = 'Stick / Unstick Thread';
$l['split_thread'] = 'Split Thread';
$l['merge_threads'] = 'Merge Threads';
$l['remove_redirects'] = 'Remove Redirects';
$l['remove_subscriptions'] = 'Remove All Subscriptions';
$l['poll'] = 'Poll:';
$l['show_results'] = 'Show Results';
$l['edit_poll'] = 'Edit poll';
$l['public_note'] = '<i class="bi bi-info-circle"></i> <span class="text-muted">This is a public poll, other users will be able to see what you voted for.</span>';
$l['total'] = 'Total';
$l['vote'] = 'Vote!';
$l['total_votes'] = '{1} vote(s)';
$l['you_voted'] = '* You voted for this item.';
$l['poll_closed'] = '<span class="text-danger"><i class="bi bi-info-circle"></i> This poll is closed.</span>';
$l['poll_closes'] = 'This poll will close on <span class="text-muted">{1}</span>';
$l['already_voted'] = 'You have already voted in this poll.';
$l['no_voting_permission'] = 'You do not have permission to vote in this poll.';
$l['undo_vote'] = 'Undo vote';
$l['quick_reply'] = 'Quick Reply';
$l['message_note'] = 'Type your reply to this message here.';
$l['signature'] = 'Signature';
$l['email_notify'] = 'Email Notification';
$l['disable_smilies'] = 'Disable Smilies';
$l['post_reply'] = 'Post Reply';
$l['post_reply_img'] = 'Post Reply';
$l['new_reply'] = 'New Reply';
$l['search_button'] = 'Search';
$l['post_thread'] = 'Post Thread';
$l['preview_post'] = 'Preview Post';
$l['rating_average'] = '{1} Vote(s) - {2} Average';
$l['rate_thread'] = 'Rate Thread';
$l['thread_rating'] = 'Rate Thread';
$l['similar_threads'] = 'Related Threads&hellip;';
$l['thread'] = 'Thread';
$l['replies'] = 'Replies';
$l['views'] = 'Views';
$l['lastpost'] = 'Last Post';
$l['messages_in_thread'] = 'Messages In This Thread';
$l['users_browsing_thread'] = 'Recently Browsing';
$l['users_browsing_thread_guests'] = '{1} Guest(s)';
$l['users_browsing_thread_invis'] = '{1} Invisible User(s)';
$l['users_browsing_thread_reading'] = 'Reading&hellip;';
$l['inline_soft_delete_posts'] = 'Soft Delete Posts';
$l['inline_restore_posts'] = 'Restore Posts';
$l['inline_delete_posts'] = 'Delete Posts Permanently';
$l['inline_merge_posts'] = 'Merge Posts';
$l['inline_split_posts'] = 'Split Posts';
$l['inline_move_posts'] = 'Move Posts';
$l['inline_approve_posts'] = 'Approve Posts';
$l['inline_unapprove_posts'] = 'Unapprove Posts';
$l['inline_post_moderation'] = 'Inline Post Moderation';
$l['inline_go'] = 'Go';
$l['clear'] = 'Clear';
$l['thread_closed'] = 'Thread Closed';
$l['no_subject'] = 'No subject';
$l['error_nonextnewest'] = 'There are no threads that are newer than the one you were previously viewing.';
$l['error_nonextoldest'] = 'There are no threads that are older than the one you were previously viewing.';
$l['quickreply_multiquote_selected'] = 'You have selected one or more posts to quote.';
$l['quickreply_multiquote_now'] = 'Quote these posts now';
$l['or'] = 'or';
$l['quickreply_multiquote_deselect'] = 'deselect them';
$l['search_thread'] = 'Search Thread';
$l['enter_keywords'] = 'Enter Keywords';
$l['view_thread_notes'] = 'Thread Notes';
$l['view_all_notes'] = 'View All Notes';
$l['save_changes'] = 'Save Changes';
$l['cancel_edit'] = 'Cancel Edit';
$l['quick_edit_update_error'] = 'There was an error editing your reply:';
$l['quick_reply_post_error'] = 'There was an error posting your reply:';
$l['quick_delete_error'] = 'There was an error deleting your reply:';
$l['quick_delete_success'] = 'The post was deleted successfully.';
$l['quick_delete_thread_success'] = 'The thread was deleted successfully.';
$l['quick_restore_error'] = 'There was an error restoring your reply:';
$l['quick_restore_success'] = 'The post was restored successfully.';
$l['post_deleted_error'] = 'You can not perform this action to a deleted post.';
