<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : English (American)
// Author of the language pack : MyBB Group
// Language pack translators website : https://mybb.com/
// Compatible version of MyBB : 1828
// Last edited in MyBB Editor by : Matty
// Last edited date : Tue, 09 Aug 2022 15:34:13 +0000
// --------------------------------------------------------------------------------

$l['nav_showteam'] = 'Forum Team';
$l['forum_team'] = 'Forum Team';
$l['moderators'] = 'Moderators';
$l['username'] = 'Username';
$l['lastvisit'] = 'Last seen';
$l['email'] = 'Email';
$l['pm'] = 'PM';
$l['mod_forums'] = 'Forum(s)';
$l['mod_groups'] = 'Group(s)';
$l['online'] = 'Online';
$l['offline'] = 'Offline';
$l['away'] = 'Away';
$l['group_leaders'] = 'Group Leaders';
$l['group_members'] = 'Member(s)';
$l['no_members'] = 'No members in this group';
$l['showteam_disabled'] = 'The forum team listing functionality has been disabled by the Administrator.';
$l['error_noteamstoshow'] = 'There are no forum staff to be shown.';
