<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : English (American)
// Author of the language pack : MyBB Group
// Language pack translators website : https://mybb.com/
// Compatible version of MyBB : 1828
// Last edited in MyBB Editor by : Matty Wjeisz
// Last edited date : Thu, 28 Jul 2022 06:39:43 +0000
// --------------------------------------------------------------------------------

$l['nav_stats'] = 'Statistics';
$l['stats_disabled'] = 'You cannot view the statistics page as it has been disabled by the Administrator.';
$l['board_stats'] = 'Statistics';
$l['none'] = 'None';
$l['totals'] = 'Totals';
$l['averages'] = 'Averages';
$l['posts'] = 'Posts';
$l['threads'] = 'Threads';
$l['members'] = 'Members';
$l['ppd'] = 'Posts per day';
$l['tpd'] = 'Threads per day';
$l['mpd'] = 'Members per day';
$l['ppm'] = 'Posts per member';
$l['tpm'] = 'Threads per member';
$l['rpt'] = 'Replies per thread';
$l['no_posts'] = 'No';
$l['general'] = 'General';
$l['newest_member'] = 'Latest Member';
$l['members_posted'] = 'Member Posts';
$l['todays_top_poster'] = 'Today\'s Top Poster<br />{1} - {2} posts';
$l['popular_forum'] = 'Most Popular<br />{1}<br />{2} posts, {3} threads';
$l['most_popular'] = 'Most Popular&hellip;';
$l['most_replied_threads'] = 'Most Replies';
$l['most_viewed_threads'] = 'Most Views';
$l['not_enough_info_stats'] = 'Sorry, but there is not enough information on this board to generate statistics. Before statistics can be generated this board needs to contain at least 1 member and 1 thread.';
$l['replies'] = 'replies';
$l['views'] = 'views';
$l['top_referrer'] = '<div class="col align-self-center text-center">
Top Referrer<br /> <strong>{1}</strong> (<strong>{2}</strong> referrals) </div>';
