<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : English (American)
// Author of the language pack : MyBB Group
// Language pack translators website : https://mybb.com/
// Compatible version of MyBB : 1828
// Last edited in MyBB Editor by : Matty Wjeisz
// Last edited date : Thu, 21 Jul 2022 09:52:02 +0000
// --------------------------------------------------------------------------------

$l['ucp_nav_width'] = '180';
$l['ucp_nav_menu'] = 'Account Settings';
$l['ucp_nav_messenger'] = 'Messages';
$l['ucp_nav_compose'] = 'New Message';
$l['ucp_nav_tracking'] = 'Tracking';
$l['ucp_nav_edit_folders'] = 'Edit Folders';
$l['ucp_nav_profile'] = 'Profile Settings';
$l['ucp_nav_edit_profile'] = 'Edit Profile';
$l['ucp_nav_edit_options'] = 'Edit Options';
$l['ucp_nav_change_email'] = 'Change Email';
$l['ucp_nav_change_pass'] = 'Change Password';
$l['ucp_nav_change_username'] = 'Change Username';
$l['ucp_nav_edit_sig'] = 'Change Signature';
$l['ucp_nav_change_avatar'] = 'Change Avatar';
$l['ucp_nav_misc'] = 'Miscellaneous';
$l['ucp_nav_editlists'] = 'Buddy/Ignore List';
$l['ucp_nav_favorite_threads'] = 'Favorite Threads';
$l['ucp_nav_subscribed_threads'] = 'Subscribed Threads';
$l['ucp_nav_forum_subscriptions'] = 'Forum Subscriptions';
$l['ucp_nav_drafts'] = 'Saved Drafts';
$l['ucp_nav_drafts_active'] = 'Saved Drafts <strong>({1})</strong>';
$l['ucp_nav_notepad'] = 'Personal Pad';
$l['ucp_nav_view_profile'] = 'View Profile';
$l['ucp_nav_home'] = 'Control Panel';
$l['ucp_nav_usergroups'] = 'Group Memberships';
$l['ucp_nav_attachments'] = 'Manage Attachments';
