# Generated by Django 5.0.1 on 2024-02-02 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_order_anonym_token_alter_order_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='showed',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
