# Generated by Django 5.0.1 on 2024-02-04 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_coupon_couponorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='couponorder',
            name='coupon',
        ),
        migrations.AddField(
            model_name='couponorder',
            name='discount',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
