# Generated by Django 5.0.1 on 2024-02-04 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_profile_anonymous_token_alter_profile_birth_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='anonymous_token',
        ),
    ]
